export const LOGIN_LOGIN = 'LOGIN_LOGIN';
export const LOGIN_AUTH = 'LOGIN_AUTH';
export const LOGIN_LOAD_PAGE = 'LOGIN_LOAD_PAGE';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const GET_AUTH_SCOPES = 'GET_AUTH_SCOPES';
export const SAVE_OAUTH_QUERY = "SAVE_OAUTH_QUERY";
export const SAVE_SESSION_FAIL_FROM = "SAVE_SESSION_FAIL_FROM";
export const SAVE_SESSION_INFO = "SAVE_SESSION_INFO";


export const GLOBAL_EMAIL = 'GLOBAL_EMAIL';



export const REGISTER_SET_COPPAID = "REGISTER_SET_COPPAID";

export const REGISTER_CHANGE_COPPA = 'REGISTER_CHANGE_COPPA';
export const REGISTER_ID_CONFIRMATION = 'REGISTER_ID_CONFIRMATION';
export const REGISTER_CREATE_ACCOUNT = 'REGISTER_CREATE_ACCOUNT';

export const REGISTER_CARD_VERIFY = 'REGISTER_CARD_VERIFY';
export const REGISTER_SHOW_QUIT = 'REGISTER_SHOW_QUIT';
export const REGISTER_CHANGE_PRIVACY = 'REGISTER_CHANGE_PRIVACY';
export const REGISTER_CHANGE_TERMS = 'REGISTER_CHANGE_TERMS';
export const REGISTER_SERVER_FAIL = 'REGISTER_SERVER_FAIL';
export const REGISTER_CREDIT_PROBLEM_PAGE = 'REGISTER_CREDIT_PROBLEM_PAGE';
export const REGISTER_CREDIT_POPUP = 'REGISTER_CREDIT_POPUP';
export const REGISTER_COPPA_CODE_SUCCESS = 'REGISTER_COPPA_CODE_SUCCESS';
export const REGISTER_COPPA_CODE = 'REGISTER_COPPA_CODE';
export const REGISTER_CREDIT_STATE = 'REGISTER_CREDIT_STATE';
export const REGISTER_FAIL = "REGISTER_FAIL";


export const REGISTER_CREDIT_VERIFY_MAIL = 'REGISTER_CREDIT_VERIFY_MAIL';
export const SETTING_ACTIVATE_STATUS = 'SETTING_ACTIVATE_STATUS';



export const REGISTER_TEST_API = 'REGISTER_TEST_API';

// Forget_Password Actions by yingray (rename 2016.06.14)
export const FORGET_PASSWORD_LOAD_PAGE          =   'FORGET_PASSWORD_LOAD_PAGE';
export const FORGET_PASSWORD_CLICK_SEND         =   'FORGET_PASSWORD_CLICK_SEND';
export const FORGET_PASSWORD_SAVE_EMAIL         =   'FORGET_PASSWORD_SAVE_EMAIL';
export const FORGET_PASSWORD_VALIDATE_EMAIL     =   'FORGET_PASSWORD_VALIDATE_EMAIL';
// Reset_Password Actions by yingray (rename 2016.06.14)
export const RESET_PASSWORD_VERIFY_TOKEN        =   'RESET_PASSWORD_VERIFY_TOKEN';
export const RESET_PASSWORD_CHANGE_PASSWORD     =   'RESET_PASSWORD_CHANGE_PASSWORD';
export const RESET_PASSWORD_SEND_PASSWORD       =   'RESET_PASSWORD_SEND_PASSWORD';
// Change_Password Actions by yingray (2016.06.15)
export const CHANGE_PASSWORD_CHANGE_PASSWORD    =   'CHANGE_PASSWORD_CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SEND_PASSWORD      =   'CHANGE_PASSWORD_SEND_PASSWORD';
export const CHANGE_PASSWORD_FAIL               =   'CHANGE_PASSWORD_FAIL';
// Password Component Actions by yingray
export const PASSWORD_LOAD_PASSWORD             =   'PASSWORD_LOAD_PASSWORD';
export const PASSWORD_CHANGE_PASSWORD           =   'PASSWORD_CHANGE_PASSWORD';
export const PASSWORD_CHECK_PASSWORD            =   'PASSWORD_CHECK_PASSWORD';
// Notification Component Actions by yingray (2016.07.12)
export const NOTIFICATION_CLICK                 =   'NOTIFICATION_CLICK';
export const NOTIFICATION                       =   'NOTIFICATION';
// Notification Component Actions by yingray (2016.07.13)
export const EMAIL_VERIFICATION                 =   'EMAIL_VERIFICATION';


export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const TEMP_SAVE_PROFILE = 'TEMP_SAVE_PROFILE';
export const PROFILE_UPDATE_SINGLE_VALUE = "PROFILE_UPDATE_SINGLE_VALUE";
export const TEMP_SAVE_KID_PROFILE = 'TEMP_SAVE_KID_PROFILE';
export const UPDATE_KID_PROFILE = 'UPDATE_KID_PROFILE';
export const LOAD_KID_PROFILE = "LOAD_KID_PROFILE";
export const GET_STATE = "GET_STATE";
export const SAVE_NAMES = "SAVE_NAMES";

//client
export const CLINET_SAVE_CLIENTID = "CLINET_SAVE_CLIENTID";
export const CLIENT_GET_CLIENTDATA = "CLIENT_LOAD_CLIENTDATA";
export const CLINET_SAVE_WINDOW_SIZE = "CLINET_SAVE_WINDOW_SIZE";


export const ASSIGN_AGENT = "ASSIGN_AGENT";
